mamba-org/boa

- README.md
Add ruamel and ruamel.yaml to installation instructions
Also specifies minimum version for conda-build (3.18.12). Unfortunately there does not seem to be a conda-build>=3.18.12 package for python 3.8.
Closes #9
> Add ruamel and ruamel.yaml to instructions

- boa/cli/build.py
Some conda channels might not have a name. E.g. something like this is a valid channel: https://conda.mydomain.tld/linux-64
> Add support for nameless channels

- boa/build.py
There are multiple unused imports, I'm removing this one as it does not exist (anymore?) and results with an `ImportError`, but I will remove more of them later with a flake8 pass
> Remove unused import

- boa/cli/mambabuild.py
Minimal change: this doesn't support glob patterns or the -k flag like
conda.
> feat: support -t argument for testing packages

- boa/cli/mambabuild.py
I've been experimenting with `mamba` in a company / corporate environment behind proxies.
Today I tried for the first time to use `boa` to build conda packages. It failed with the error message `SSL peer certificate or SSH remote key was not OK` when trying to update the index after calling the `get_index()` function on the mamba's `utils.py` module, when trying to call:
```python
dlist.download(True)
```
I looked at `mamba` source code, and I noticed that before many commands (for example, `install`) are executed there is a call to `init_api_context()`.
I added that call in the beginning of the `mambabuild` command and it worked: the build passed.
However so far I've noticed it's always getting from cached data.
So I'm not sure if this is the final solution to the problem.
> FIX: fetching index repodata - SSL cert failure

- boa/cli/mambabuild.py
@xhochy this is a small quality of life improvement for mambabuild which _might_ fix your issue (although I couldn't recreate your exact issue, just another one when `conda-bld` was completely removed).
> mkdir outputfolder if not exist in mambabuild

- boa/cli/mambabuild.py
- boa/core/solver.py
- boa/core/utils.py
This is the proposed fix for #111 
Thanks @wolfv for the help and the guidance here.
I couldn't easily reuse the existing `get_solver()` function from `solver.py` because I wasn't sure about the current behaviour there when it creates the solvers for the first time, it's passing an empty list of channel_urls, which is different from the behaviour when calling from `mamba_get_install_actions()`.
> FIX: solver lookup for noarch

- boa/cli/mambabuild.py
@wolfv as we discussed I'm extracting here the 2 methods `prepare()` and `call_conda_build()` to make it easier to call `mambabuild` programatically without requiring duplicating the same code elsewhere. Now `main()` is just a glue function that calls the preparation steps, gets the Config returned and delegates it to `conda-build`.
> Refactoring to extract a minimal mambabuild API

- boa/cli/boa.py
- boa/core/solver.py
Remove redundant setting of `api_ctx` now that it's done by calling `mamba.utils.init_api_context` in `mambabuild`.
Resolves the issue detailed here: https://github.com/mamba-org/boa/issues/124
> Fix MambaSolver ignoring set pkgs_dirs

- boa/core/metadata.py
- boa/core/recipe_output.py
This properly adds constrains metadata when `run_constrained` is in metadata.
> Fix run constrains metadata

- README.md
`boa` depends on `mamba`.
We get `ModuleNotFoundError: No module named 'mamba.utils'` if `mamba` is not installed in the environment.
> Install mamba in the dev environment as well

- boa/core/recipe_output.py
- boa/core/solver.py
- boa/core/test.py
A few comments:
1. Clobber Warnings still appear :/
2. New output also appears in the form of:
```
INFO: activate_clang_osx-64.sh made the following environmental changes:
+AR=x86_64-apple-darwin13.4.0-ar
+AS=x86_64-apple-darwin13.4.0-as
+CC=x86_64-apple-darwin13.4.0-clang
...
```
3. Returning `MambaSolver([], subdir, config, output_folder)` directly instead of using caching somehow breaks the
`boa build -i` with a segmentation fault.
> remove clobber warnings in boa interactive build

- boa/cli/mambabuild.py
This PR fixes the format of the `--output` action for `mambabuild` to match conda-build.
> Fix format of conda mambabuild --output

- boa/cli/mambabuild.py
This adds support for testing multiple files as reported in #224 
Solution is to handle it the same way that `conda-build` does here: https://github.com/conda/conda-build/blob/4ec7d8a7625649b555abc1aad000a141e9d067c5/conda_build/cli/main_build.py#L443-L464
Its not beautiful but works
> mambabuild --test support for multiple files

- boa/core/conda_build_spec.py
A simple recipe like https://github.com/RoboStack/ros-galactic/tree/main/additional_recipes/ros2-distro-mutex fails with:
```bash
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│                                                                                                  │
│ /Users/fischert/mambaforge/lib/python3.9/site-packages/boa/core/run_build.py:302 in build_recipe │
│                                                                                                  │
│   299 │   │   │   o.finalize_solve(sorted_outputs)                                               │
│   300 │   │   │                                                                                  │
│   301 │   │   │   meta = MetaData(recipe_path, o) …
```
> Fix AttributeError in conda_build_spec in case there is no pin

- .pre-commit-config.yaml
- boa/cli/boa.py
- boa/core/build.py
- boa/core/run_build.py
- boa/core/utils.py
- tests/test_rendering.py
The arguments `--build-id-pat`, `--no-remove-work-dir`, `--keep-old-work`, `--prefix-length`, `--croot` are occasionally used in conjunction with each other in order to ensure a consistent predictable build location that can be used by tools like ccache.
The zstd parameter (and pkg version) configuration option bring boa to parity with conda-build in supporting the `.conda` format
> Support additional conda-build command line flags in `boa build`

- boa/core/metadata.py
- tests/test_boa_build.py
- tests/tests-v2/metapackage-channel-pin/recipe.yaml
This is a rarely used feature from conda-build that was not working as expected.
> Allow `boa build` to support channel pins in packages

- boa/cli/mambabuild.py
- tests/env.yml
- tests/recipes/dep_error_has_constaint/meta.yaml
- tests/recipes/dep_error_needed_by/meta.yaml
- tests/recipes/dep_error_nothing_provides/meta.yaml
- tests/recipes/dep_error_package_requires/meta.yaml
- tests/test_mambabuild.py
This is a follow-up to gh-301 to fix/improve the dependency extraction in `mambabuild.parse_problems` for different cases.
> mambabuild: dependency error parse improvements

- boa/core/environ.py
This change came directly from the issue filed by Jon, who I work with.
> For issue 313 use os.path.normpath not os.normpath when setting git_url.

- boa/schemas/model.py
- boa/schemas/recipe.v1.json
#311 - fix, sorry commit message has wrong issue id
sources:
git_url: ..
destination -> folder:
the actual download of the source is taking place in the conda_build::source.provide.L850 which expects a folder in the schema name
boa::boa.core.build.py:L565
def _try_download(m, interactive):
try:
source.provide(m)
conda_build::source.provide.py:L850
folder = source_dict.get('folder')
> #311 - reverting schema changes

- boa/core/recipe_output.py
- tests/recipes-v2/pin_compatible/recipe.yaml
Ran into this issue when I was trying to upgrade to a newer version of boa, going from `0.7.1` directly to `0.14.0` not sure when this stopped working. 
Added test to the boa build recipes. The test is pretty specific to my use case but my knowledge on the pin compatible mechanism is too small to make any more meaning full test.
> Fix pin_compatible

- boa/cli/boa.py
- boa/core/run_build.py
This allows passing the variant from the cli to match conda build.
Eg  `boa build recipe --python=3.11`
> Support passing build variants from cli

- boa/cli/boa.py
- boa/cli/validate.py
- boa/core/render.py
- boa/core/run_build.py
- boa/core/test.py
Instead of having a separate recipe.yaml (which since boa is now valid YAML), this makes it possible to represent a recipe directly inside a pyproject.toml file, which makes it a lot more streamlined to build internal packages where code & recipe are not separated from each other.
This is further explained in and closes #323, and implements only the second example - a `load_toml()` function might be nice as well, but as there's currently AFAIK also not a ``load_yaml()` function anymore in boa due to the new spec, I decided not to pusue that approach further.
> Make it possible to include the recipe.yaml inside a pyproject.toml

- boa/cli/boa.py
- boa/cli/test.py
- boa/core/test.py
Fixes #326 - `boa test xyz.tar.bz2` can now be used to test a package seperate from the build process.
Also includes an argument "--extra-deps", as known from conda-build, to add additional packages to the testing environment. Use case for that would be for example to a) specify a Python version for a noarch package, or b) first test the package, then use the test environment (e.g. with the --extra-deps mypy & pylint) to run further linting or type checking steps in a CI.
> Implement separate "boa test" command to fix #326

- boa/core/run_build.py
Fix #284 
As noted in the linked issue, it looks like the config isn't updated with any of the information from the variant config files passed from the command line (at least, not before the call to `find_all_recipes` in `run_build.py`). The current version of the PR fixes the issue of the `cdt_name` not being recognized by just using the first of the resolved variant configs, which may be a hack.
> fix: add cdt_name to config.variants

- boa/cli/boa.py
- boa/cli/mambabuild.py
- boa/core/solver.py
- boa/core/utils.py
- tests/env.yml
Any code from the `mamba` pure Python package is legacy that no one is able to maintain/understand.
Copy relevant functions here and drop the `mamba` dependency to use only `libmambapy`.
> Don't use mamba package

- boa/core/test.py
- setup.py
With the latest release of `ruamel.yaml` version `0.18.2`, now `safe_load` is removed. In this PR updating a remaining usage of it.
> replacing use of deprecated ruamel.yaml.safe_load

- boa/cli/convert.py
> Update ruamel.yaml reference to the new api

- boa/cli/mambabuild.py
- boa/core/build.py
- boa/core/run_build.py
- boa/core/test.py
- tests/env.yml
> Use `update_index` from conda-index directly

- .github/workflows/lint.yml
- .github/workflows/main.yml
- boa/cli/boa.py
- boa/cli/mambabuild.py
- boa/core/build.py
- boa/core/metadata.py
- boa/core/monkey_patch_emscripten.py
- boa/core/solver.py
- boa/core/test.py
- boa/core/utils.py
- setup.py
- tests/env.yml
This updates `boa` for compatibility with current/upcoming `conda-build` versions.
Overview:
- Add/change CI jobs to test against lowest supported as well as `conda`/`conda-build` pre-release versions.
- Add `boltons` dependency since `conda._vendor.boltons` is being removed.
- Raise minimum `conda-build` to `3.25` (semi-arbitrarily chosen; `>=3.25` include, e.g., fixes for [downstream tests](https://github.com/conda/conda-build/issues/4750)).
- Removes usage of to-be-deprecated `conda_build.conda_interface`.
- Fixes gh-388 .
> Update for conda/conda-build deprecations

- CHANGELOG.md
- boa/_version.py
cc @mbargull lmk if that's fine with you! :)
> release 0.17.0
