mamba-org/boa

boa/cli/boa.py
boa/cli/mambabuild.py

Flexible platform subdir

---

README.md

Required after https://github.com/mamba-org/boa/commit/e652c611a19fe5ab04127202b519e43f240b0dee

Fix min conda-build version

---

boa/cli/mambabuild.py
setup.py

Pretty much just a copy of https://github.com/mamba-org/mamba/pull/370
Closes: #31

fix: use binstar token from anaconda-client

---

.github/workflows/main.yml
README.md

It's passing, see https://github.com/martinRenou/boa/pull/1

Add Github actions

---

boa/cli/mambabuild.py

Might fix #17 ?
We are not testing mambabuild, maybe I should add a test for it first.

Allow passing custom variants files

---

boa/core/build.py

Fix https://github.com/mamba-org/boa/issues/47

Boa build: Improve build error message and quit early

---

boa/core/build.py
boa/core/metadata.py
boa/core/recipe_output.py

Fix https://github.com/mamba-org/boa/issues/55

Early quit on patch error

---

boa/core/recipe_output.py
setup.py

@wolfv the metadata.py module could use more pathlib but the rest is fine with `os.path` b/c you are not really doing much with paths there.

use pathlib

---

boa/cli/boa.py
boa/core/build.py
boa/core/render.py
boa/core/run_build.py
boa/tui/tui.py
schemas/recipe.v1.json
setup.py

This adds an interactive mode on failed builds ... lots of things that still need to be done but already starts to be kinda cool!
Quick Demo:
[![asciicast](https://asciinema.org/a/76cUZmNmtjFCBuvjBW5fzRYx2.svg)](https://asciinema.org/a/76cUZmNmtjFCBuvjBW5fzRYx2)

Text User Interface (TUI)

---

boa/cli/mambabuild.py

@gabrielcnr does that fix the issue for you by any chance?

fix channel downloading

---

boa/core/build.py
boa/core/run_build.py

the annoying sha256 sum error is a thing of the past!

auto-fix recipe if hash changed

---

boa/cli/convert.py
boa/cli/transmute.py
boa/core/build.py
boa/core/metadata.py
boa/core/recipe_handling.py
boa/core/recipe_output.py
boa/core/run_build.py
boa/core/test.py
boa/core/utils.py
setup.py
tests/env.yml

Initial ported code from conda-build

Start adding test capabilities to boa

---

boa/cli/mambabuild.py
boa/core/solver.py

add proper output folder handling to mambabuild

---

boa/cli/mambabuild.py
boa/core/solver.py

use passed channels and virtual packages

---

boa/core/solver.py

IDK why we had this one. Now it's gone forever!
Fixes #122

remove unicode char that is troubling Windows

---

boa/cli/mambabuild.py
tests/test_boa_build.py
tests/test_mambabuild.py

Added a test to prevent future regression

Fix conda mambabuild --no-test

---

README.md

Reformatted the readme file. 
Also Fixes #173

Updated boa README.md file

---

boa/tui/tui.py

fix ls under macOS

---

boa/cli/mambabuild.py
boa/core/config.py
boa/core/solver.py

Fixes https://github.com/mamba-org/boa/issues/157

output paths on --output flag

---

boa/core/test.py

Assumes that contents of `test.yaml` are:
```
exists:
site_packages:
- numpy
lib:
- libcurl
include:
- xtensor
- xtensor.hpp
- xtensor/xarray.hpp
bin:
- f2py
- f2py3
- curl-config
cmake_find:
- xtensor
pkg_config:
- xtensor
file:
- ssl/cacert.pem
- ssl/misc
glob:
- doc/**/Copyright.txt
```

file existence macros

---

boa/_version.py
boa/cli/mambabuild.py

clean up and release 0.7.1

---

boa/core/render.py

This removes a source of validation errors.

normalize version to package outputs

---

boa/core/metadata.py

Read binary_relocation value

---

boa/core/test.py

Fix error in test when include_recipe is false

---

boa/core/build.py
boa/core/environ.py
boa/core/render.py
boa/core/run_build.py
boa/core/test.py
boa/core/windows.py
docs/source/advanced_recipe_spec.md
tests/recipes-v2/environ/recipe.yaml
tests/test_boa_build.py
tests/test_rendering.py

cc @dhirschfeld @mariusvniekerk 
There you go :)

Add environ to context

---

boa/cli/mambabuild.py

See for eg: https://app.travis-ci.com/github/conda-forge/binutils-feedstock/jobs/585739088

Fix parsing problems when test_downstreams is called

---

boa/core/recipe_output.py
boa/schemas/model.py
boa/schemas/recipe.v1.json

This adds proper types for run_exports in the recipe.

Run export types

---

boa/core/recipe_handling.py

Only copy the recipe if it exists

---

boa/core/render.py

Resolves https://github.com/mamba-org/boa/issues/353

Open recipe file in binary format
